name: Check update servers

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  checkUpdateServers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: { ref: develop }
      - name: Checking...👨‍💻 
        run: |
          curl -L -X POST '${{vars.LINK_TRY_UPDATE_HOSTS_SERVERS}}' -H 'Authorization: Bearer ${{secrets.SUPABASE_KEY_FUNCTIONS}}'